### ISSUE TITLE
Linux Build cannot connect to GitHub Enterprise

### ISSUE THREAD

**Issue by jwood13** [shiftkey/desktop#13]
### Description

When trying to sign into a github enterprise server, github desktop responds with `The GitHub Enterprise version does not support GitHub Desktop. Talk to your server's administrator about upgrading to the latest version of GitHub Enterprise`
This only occurs using the Linux build, I am able to do it easily with the Windows build

### Version

**GitHub Desktop version:** 1.011 
Git Hub Enterprise version: 2.11

**OS version:** Ubuntu 16.04.3 LTS

### Steps to Reproduce

1. Open Options
1. Select Sign in under Enterprise
1. Enter Valid Credentials
1. Click Sign in
1. Look at the error code

Selecting Sign in using your browser also fails

**Expected behavior:** Connect to a GitHub Enterprise (2.11) Server

**Actual behavior:** Error Message

**Reproduces how often:** Every Time

### Logs
2017-12-18T04:16:50.306Z - info: [ui] [SignInStore] initializing OAuth flow
2017-12-18T04:16:50.309Z - info: [main] opening in browser: https://github.[REMOVED]/login/oauth/authorize?client_id=[REMOVED]&scope=repo%20user&state=[REMOVED]

**Comment by shiftkey** [comment]
I know what this is. This is an oversight of the packaging process, and it includes the development OAuth app details - which means GitHub Enterprise doesn't know about it. I'll make sure this is right for the next build.

**Comment by shiftkey** [comment]
This has been fixed with [1.0.11 RC3](https://github.com/shiftkey/desktop/releases/tag/release-1.0.11-linux3).

**Comment by wanjizheng** [comment]
Sorry, but this problem still exists in the later release.  Please could you let me know how to fix this so that I could modify the code myself?

**Comment by j-f1** [comment]
@wanjizheng Can you open a new issue so we can figure out what’s going on in your case?
