### ISSUE TITLE
discarding changes takes a significant amount of time to complete

### ISSUE THREAD

**Issue by Jick-study** [shiftkey/desktop#332]
升级最新版本后发现：当我对改变的文件进行回滚时，软件会卡顿，并且回滚速度很慢。
我已经将版本回滚到了：2.5.3 Linux RC1，上个版本没有上述问题。
电脑系统：ubuntu-18.04

**Comment by shiftkey** [comment]
@fy287216637 thanks for the report! 

I'm not sure I understand the behaviour you're seeing and steps to reproduce it - would you be able to fill out the template (in Chinese is fine) as best as you can?

**Comment by Jick-study** [comment]
![11111](https://user-images.githubusercontent.com/29773167/91782633-39c4b700-ec30-11ea-8df2-00ce132176dc.png)
执行回滚操作时，软件会卡住，必须等待好久才可以执行完毕，然而上个版本会非常快的回滚完成

**Comment by shiftkey** [comment]
@fy287216637 thanks for that information!. I believe this is an intentional change related to https://github.com/desktop/desktop/pull/10143.

In previous releases the dialog would close before the actual operation of moving files to the trash had completed.

In the latest release are you seeing the progress indicator in the header while this is occurring?

<img width="491" src="https://user-images.githubusercontent.com/634063/86594716-cb4cdb00-bf97-11ea-8065-ba1d1914d4be.png">

If this is visible and spinning, I believe this is working as expected.

**Comment by Jick-study** [comment]
虽然有旋转提示，但是会很慢。
上个版本选择回滚一般 1秒到2秒就会完成，然而这个版本会让系统卡顿并且得十几秒左右才会完成！！！

**Comment by Mrlinkwii** [comment]
@fy287216637  the reason it takes 10 seconds to do unlike the 2 seconds like in previous releases  i think is released to #329

**Comment by Jick-study** [comment]
@shiftkey 您好，最新版本依旧有这个问题，选择回滚时界面会卡顿很久。
我只能再次将版本回退为2.5.3

**Comment by johngrabner** [comment]
let me know if you need any additional data collected.

**Comment by lgarczyn** [comment]
Same issue on ubuntu 20.04.1 LTS and github desktop Version 2.5.4-linux1

**Comment by alvaro-octal** [comment]
- Ubuntu 20.04
- Version 2.6.2-linux1

Keeps happening. As far as I've seen, the changes are discarded "instantly", but the loading modal stays there  (if I close GH Desktop, when I reopen the file is no longer there (and sometimes this is faster than just waiting))

**Comment by Dunemask** [comment]
Issues applies to pushes, pulls, commits, discarding commits.
Simply Refocusing the Window seems to force the application to sync (This could however just cause the application to un-sync itself with the actual git process in the background).

* Pop!_OS 20.10 x86_64
* Github Desktop Version 2.6.3-linux1
* Git Version 2.27.0

**Comment by mimbrero** [comment]
> Issues applies to pushes, pulls, commits, discarding commits.
> Simply Refocusing the Window seems to force the application to sync (This could however just cause the application to un-sync itself with the actual git process in the background).
> 
>     * Pop!_OS 20.10 x86_64
> 
>     * Github Desktop Version 2.6.3-linux1
> 
>     * Git Version 2.27.0

Exactly the same for me, Pop!_OS 20.10 x86_64

**Comment by matshou** [comment]
> Issues applies to pushes, pulls, commits, discarding commits.

I've got the same problem, committing takes significantly longer then on Windows platform.

**Comment by ggrrll** [comment]
same issue here on
* Linux Mint 20.1 -- Cinnamon 4.8.6
* GH D v. 2.6.2

(thanks for filing the issue )

**Comment by Mrlinkwii** [comment]
@ggrrll  can you please try the latest release available if your using the the artifacts form the release page  ?

**Comment by ggrrll** [comment]
@Mrlinkwii still the same issues, on 

GH D v. 2.8.1 

-- the pop-up stays stuck for long...until I resize (zoom in/out)

**Comment by shiftkey** [comment]
I've published a new build with what several folk believe is the fix for this issue - please try it out and let me know if it works for you [`2.8.1-linux3`](https://github.com/shiftkey/desktop/releases/tag/release-2.8.1-linux3).

**Comment by matshou** [comment]
Xubuntu 20.04
The new build fixes committing on my side but pushing still hangs until the application is refocused.

**Comment by tImIbreakdown** [comment]
Kubuntu 21.04
For me, on the latest version (2.8.1-linux3) the problem is solved . Now I don't need to resize, fold / unfold, refocus, etc.

**Comment by shiftkey** [comment]
> The new build fixes committing on my side but pushing still hangs until the application is refocused.

@yooksi please open a new bug report and provide as much detail as possible to help me understand what you're seeing

**Comment by orrinoAriel** [comment]
Same issue here, push, fetch and pull are the problem now...but I think that is a visual issue, as all said if I switch and return, all is OK
GH Desktop: Version 2.8.1-linux3
Linux: Linux Mint 20.1 Cinnamon

**Comment by ghost** [comment]
The problem still remains. If I change the screen and go back it works.
GitHub Desktop: 2.8.1-linux3
Linux: Ubuntu 20.04.2 LTS

**Comment by shiftkey** [comment]
@orrinoAriel please check the issue tracker for other issues, as I want to see if we can close out this original issue.

@everton-matos please clarify which behaviour you are referring to - there's a lot of extra discussion in this issue which I'm trying to sort through but I want to focus on the original issue: discarding changes.

**Comment by ghost** [comment]
Sorry. **Pushing** and **Fetching** origin  still hangs while not changing the screen and back

**Comment by orrinoAriel** [comment]
@shiftkey from my side, yes, you can close this ticket and we can continue with the other issue in his corresponding ticket

**Comment by shiftkey** [comment]
I think #508 is the best place to follow along with that work. Thanks @everton-matos @orrinoAriel for clarifying.

**Comment by shiftkey** [comment]
Closing this out as I believe the original problem has been resolved.
