### ISSUE TITLE
Failed signing (gpg2) using Flatpak

### ISSUE THREAD

**Issue by shgysk8zer0** [shiftkey/desktop#565]
### Describe the bug

```
error: cannot run gpg2: No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object
```

### Version & OS

Version 2.9.0-linux4 (x64) [flatpak](https://flathub.org/apps/details/io.github.shiftey.Desktop)

Fedora 29

### Steps to reproduce the behavior

1. Setup `git config` to sign commits
2. Open a repo in GitHub Desktop
3. Make some changes
4. Commit

### Expected behavior

A signed commit should be created

### Actual behavior

Commit fails, as the flatpak version seems to be lacking permission to `gpg2` (maybe just `gpg` on some systems).

### Screenshots

![](https://i.imgur.com/28nrNNu.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by shiftkey** [comment]
cc @advaithm for visibility

**Comment by shiftkey** [comment]
> 1. Setup `git config` to sign commits

@shgysk8zer0 can you share the specific commands you have set?

**Comment by Lunarequest** [comment]
We don't ship gpg in the flatpak. I'll add it to the build.

**Comment by Lunarequest** [comment]
I'm adding the lts version of gpg to the build. this should be fine unless someone uses a feature not present in lts. A update should be out soon with gpg installed in the container

**Comment by Lunarequest** [comment]
I've hit a dead end where I get `gpg: signing failed: Inappropriate ioctl for device`. I've got pinentry installed so no idea why it is not launching it. any ideas are appreciated

**Comment by TommyTran732** [comment]
> I've hit a dead end where I get `gpg: signing failed: Inappropriate ioctl for device`. I've got pinentry installed so no idea why it is not launching it. any ideas are appreciated

Have you tried setting the GPG_TTY variable?

**Comment by Lunarequest** [comment]
> > I've hit a dead end where I get `gpg: signing failed: Inappropriate ioctl for device`. I've got pinentry installed so no idea why it is not launching it. any ideas are appreciated
> 
> Have you tried setting the GPG_TTY variable?

Yes you get a bad configuration error

**Comment by Lunarequest** [comment]
I've fixed this in the latest commit, I'll push a release soon

**Comment by shiftkey** [comment]
> I've fixed this in the latest commit, I'll push a release soon

Closing this out as I assume this has been resolved downstream

**Comment by noClaps** [comment]
Any update on this? Flatpak (3.0.0-linux2) still doesn't have GPG support.

**Comment by Lunarequest** [comment]
It has been resolved downstream. If you setup gpg as shown here https://gist.github.com/xavierfoucrier/c156027fcc6ae23bcee1204199f177da and have gpg-agent running before starting GitHub desktop it should work.

**Comment by noClaps** [comment]
It's still giving me the same error:

```
error: gpg failed to sign the data
fatal: failed to write commit object
```
I have done the following:
1. Followed instructions given in the link
    - `git config --global gpg.program` gives me `gpg` as an output
    - `git config --global commit.gpgSign` gives me `true` as an output
    - All other git config options are as I want them to be, and match the options provided in the link

2. Ran `gpg-agent --daemon`
    - Running `gpg-agent` gives me `gpg-agent running and available` as an output

It still doesn't work for me.

OS: Fedora 36 Workstation

**Comment by Lunarequest** [comment]
Try setting the pinentry to a working gui version in your gpg agent config

**Comment by noClaps** [comment]
Typing in `gpgconf` into my terminal gives me
```
pinentry:Passphrase Entry:/usr/bin/pinentry
```
Looking in the `/usr/bin/` directory shows me `pinentry`, `pinentry-curses`, and `pinentry-gnome3`, so should I change it to one of those?

**Comment by Lunarequest** [comment]
Change it to the gnome3 one.

**Comment by noClaps** [comment]
How would I do that? I'm sorry, I'm not very good at Linux CLI.
